// examples/react-demo/src/App.jsx
import './App.css';
import MergeTableCells from 'merge-table-cells';
import testData from '@local/test-data';

function App() {
  const columns = [
    { title: '大区', prop: 'area' },
    { title: '省/直辖市', prop: 'province' },
    { title: '城市', prop: 'city' },
    { title: '网点', prop: 'store' },
    { title: '销售额（万元）', prop: 'sales' }
  ];
  const mergeHandle = new MergeTableCells(['area', 'province', 'city']);
  const tableData = mergeHandle.format(testData);
  const getSpan = (prop, row) => {
    const { rowspan, colspan } = mergeHandle.span(prop, row);
    return [rowspan, colspan];
  }

  return (
    <div>
      <table>
        <thead>
          <tr>
            {
              columns.map(item => <th>{ item.title }</th>)
            }
          </tr>
        </thead>
        <tbody>
            {
              tableData.map(row => 
                <tr>{
                  columns.map(col => getSpan(col.prop, row).includes(0) ? 
                    null : 
                    <td {...mergeHandle.span(col.prop, row)}>{ row[col.prop] }</td>
                  )
                }</tr>
              )
            }
        </tbody>
      </table>
    </div>
  )
}

export default App

// examples/angular-tinyng/src/app/app.component.ts
import { Component } from '@angular/core';
import { TiTableColumns, TiTableRowData, TiTableSrcData } from '@opentiny/ng';
import testData from '@local/test-data';
import MergeTableCells from 'merge-table-cells';

const mergeHandle = new MergeTableCells(['area', 'province', 'city']);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  displayedData: Array<TiTableRowData> = [];
  srcData: TiTableSrcData = {
    data: mergeHandle.format(structuredClone(testData)),
    state: {
      searched: false,
      paginated: false,
      sorted: false
    }
  };
  columns: Array<TiTableColumns> = [
    { title: '大区', key: 'area' },
    { title: '省/直辖市', key: 'province' },
    { title: '城市', key: 'city' },
    { title: '网点', key: 'store' },
    { title: '销售额（万元）', key: 'sales' }
  ];

  public span = mergeHandle.span
}

<ti-table [srcData]="srcData" [(displayedData)]="displayedData">
  <table>
    <thead>
      <tr>
        <th *ngFor="let column of columns">{{ column.title }}</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let row of displayedData">
        <ng-container *ngFor="let column of columns">
          <td *ngIf="![
                row['_span']?.rowspan[column['key']],
                row['_span']?.colspan[column['key']]
              ].includes(0)"
              [attr.rowspan]="row['_span']?.rowspan[column['key']]"
              [attr.colspan]="row['_span']?.colspan[column['key']]">
            {{ row[column['key']] }}
          </td>
        </ng-container>
      </tr>
    </tbody>
  </table>
</ti-table>
